# Introducción a Deep Learning

Este es el taller introductorio a cómo funciona Deep Learning. Si no sabes Python, no te preocupes, es muy fácil de utilizar. Esto es un cuaderno de Jupyter. Los cuadernos de Jupyter son muy útiles ya que permiten tener celdas de texto (como esta) y celdas de Python. Todo se mantiene en un ambiente, por lo cuál las variables se mantienen mientras tengas el cuaderno abierto. Esto quiere decir que podemos utilizar variables de una celda en otra celda. Este cuaderno sólo está para ayudarte a empezar con las herramientas que vamos a utilizar. Al final hay una sección con las soluciones a los problemas.

En la siguiente celda importamos dos librerías que vamos a utilizar: pandas y numpy.
    
* [Pandas](https://pandas.pydata.org/): Estructuras de datos fáciles de usar para información más compleja. Aquí sólo vamos a utilizar [DataFrame](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html), una estructura muy similar a una tabla. 
* [NumPy](http://www.numpy.org/): Esta librería la vamos a usar extensivamente a través del curso. NumPy tiene herramientas para computación científica muy potentes. Por ejemplo, utilizaremos numpy.array, los cuales son mucho más compactos. Esto es muy importante cuando empecemos a utilizar cientos de miles de ejemplos. [Una explicación un poco más detallada](https://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

In [34]:
import pandas as pd
import numpy as np

Si eres completamente nuevo en Python, no te preocupes. Python tiene una sintaxis muy sencilla y concisa, por lo que es muy fácil de aprender mientras vayas desarrollando.

In [267]:
test = "Hola mundo"

In [268]:
print("test: ", test)

test:  Hola mundo


## Intro a Python
Empezaremos con una introducción de Python. Esta será breve porque Python es sencillo y hay muchos recursos donde aprenderlo en muy poco tiempo. Si te sientes cómodo con Python, salta a la sección del Perceptrón.

Esto es una variable. Como ven, no se debe asignar el tipo.

In [2]:
a = 10
a

10

El output de una celda de Python es la última expresión del programa. 

También podemos asignar varias variables a la vez.

In [6]:
a, b = 10, 5
print(a)
print(b)

10
5


In [ ]:
# Esto es un comentario
if a > b:
    print("A es más grande")
else:
    print("B es más grande")

Listas

In [12]:
lst = [2, 4, 6, 8, 10, 12, 14]
print(lst)

[2, 4, 6, 8, 10, 12, 14]


In [21]:
# Aquí accedemos a los valores de la lista de diferentes maneras.
print(lst[0])
print(lst[-1])
print(lst[1:3])# Esto es un slice. Te permite acceder a varios elementos a la vez
print(lst[1:5])
print(lst[2:]) # ¿Podrías explicar qué está ocurriendo aquí?

2
14
[4, 6]
[4, 6, 8, 10]
[6, 8, 10, 12, 14]


In [14]:
for i in lst:
    print(i)

2
4
6
8
10
12
14


In [15]:
for i in range(5):
    print(i)

0
1
2
3
4


In [16]:
frutas = ["manzana", "peras", "platanos"]
for i, item in enumerate(frutas):
    print(i, item)

0 manzana
1 peras
2 platanos


In [17]:
def suma(nums):
    """
    Este es un comentario de muchas líneas. Es buena práctica utilizarlos para 
    describir funciones y al inicio de cada archivo.
    """
    total = 0
    for n in nums:
        total = total + n
    return total
suma(lst)

56

In [20]:
sum(lst)

56

Hay *muchas* cosas de Python que no hemos visitado. Si quieren aprender más, hay muchos recursos. Aquí hemos visitado los temas básicos (variables, condicionales, listas, iteraciones, funciones), pero hay muchos temas como clases, funciones lambda y mucho más. 

Con estas herramientas deberían ser capaces de empezar a desarrollar los siguientes problemas.

## Perceptrón

Un perceptrón nos ayuda a tomar decisiones. Por el momento hemos visto que se puede hacer para ver si ir a un festival de quesos o aceptar alumnos, pero lo podemos hacer para todo tipo de cosas. Podemos representar operaciones como NOT, AND, NAND y OR con un perceptrón.

Haremos, primero, un NOT de ejemplo. El NOT tiene un input nada más. Si el input es 0, NOT 0 es verdadero. Si es 1, NOT 1 es falso. Por lo tanto, debemos ajustar dos parámetros: el peso y el bias. Queremos que cuando hagamos la operación input * weight + bias (esta es la fórmula del perceptrón, sólo que ahora tenemos un elemento), si el resultado es mayor o igual a 0, se active la neurona (es decir, devuelva verdadero).

In [53]:
test_inputs = [0, 1]

weight = -1
bias = 0.5

for i in test_inputs:
    linear_combination = i*weight + bias
    output = linear_combination >= 0
    print("Combinacion linear: ", linear_combination)
    print("Output: ", output)

Combinacion linear:  0.5
Output:  True
Combinacion linear:  -0.5
Output:  False


En esta sección vamos a implementar un perceptrón básico. Este perceptrón funcionará como una compuerta AND. No te desmotives si no lograr encontrar la solución, al final están las soluciones. 

A diferencia del NOT, para la compuerta AND tenemos dos entradas, por lo tanto, tenemos dos pesos que asignar y un bias. En la siguiente celda ajusta los pesos y bias. Puedes correr la otra celda para ver los resultados en la tabla de verdad. 

In [38]:
# TODO: Asignar los pesos y el bias para una compuerta AND
weight1 = 1
weight2 = 1
bias = 0

In [39]:
# No cambies esta celda, pero te sugiero revisarla

# Estos son los cuatro casos de la tabla de verdad que vamos a probar.
test_inputs = [(0, 0), (0, 1), (1, 0), (1, 1)]
correct_outputs = [False, False, False, True]
outputs = []

# Vamos a ir generando el output y viendo si la respuesta está bien
for test_input, correct_output in zip(test_inputs, correct_outputs):
    # Aquí sumamos la multiplicación de las entradas con sus pesos, más el bias.
    linear_combination = weight1 * test_input[0] + weight2 * test_input[1] + bias
    
    # Si la combinación lineal es positiva, el perceptrón se encenderá
    output = int(linear_combination >= 0)
    
    # Revisamos si la respuesta está bien
    is_correct_string = 'Si' if output == correct_output else 'No'
    outputs.append([test_input[0], test_input[1], linear_combination, output, is_correct_string])

# Print output
num_wrong = len([output[4] for output in outputs if output[4] == 'No'])
output_frame = pd.DataFrame(outputs, columns=['Input 1', '  Input 2', '  Combinacion Lineal', '  Activation Output', '  Es correcto'])
if not num_wrong:
    print('¡Muy bien!  Tuviste todas bien.\n')
else:
    print('Tuviste {} errores.  ¡Sigue intentando!\n'.format(num_wrong))
print(output_frame.to_string(index=False))


¡Muy bien!  Tuviste todas bien.

Input 1    Input 2    Combinacion Lineal    Activation Output   Es correcto
      0          0                  -1.0                    0            Si
      0          1                  -0.4                    0            Si
      1          0                  -0.4                    0            Si
      1          1                   0.2                    1            Si


## Funciones de Activación

Como vimos antes, el perceptrón usa como función de activación una función escalón. Aunque esta está bien para explicar cómo funciona la neurona, normalmente queremos que nuestro input pueda tener diferentes valores que no vayan de 0 a 1.

La función sigmoidal da como resultados números que van de 0 a 1. Recuerda, la entrada de esta función es la combinación lineal de la neurona. Esto quiere decir que primero multiplicamos los valores por sus pesos y a eso le sumamos el bias. Esta es la entrada de la neurona, y la neurona se activa según la función. En el caso de la sigmoidal, es la siguiente:

![Funcion Sigmoidal](https://www.safaribooksonline.com/library/view/deep-learning-with/9781787128422/assets/image_01_068.jpg)

In [49]:
def sigmoid(x):
    """
    TODO: Implement sigmoid function
    Use the method np.exp().
    
    Arguments:
    x: A value
    
    Return:
    s: The sigmoid of x
    """ 
    return 

# No modifiques esto. Aquí estamos creando dos arreglos utilizando la librería NumPy. Esto lo usaremos de prueba
inputs = np.array([0.7, -0.3])
weights = np.array([0.1, 0.8])
bias = -0.1

# TODO: Calcula la combinación linear. Recuerda que puedes utilizar el método .dot en un np.array. 
# Recuerda, la combinación lineal es el producto punto de la entrada y sus pesos, y a eso se le suma el bias.
linear_combination = 

# TODO: Activa la neurona utilizando la función sigmoidal que acabas de implementar
output = 

## No modifiques lo siguiente
print('Output:', output)

if int(output*10000) == 4329:
    print("El output está bien")
else:
    print("El output está mal")

SyntaxError: invalid syntax (<ipython-input-49-1bb2c9468d80>, line 21)

In [43]:
sigmoid(-5)

0.0066928509242848554

In [44]:
sigmoid(5)

0.9933071490757153

In [45]:
sigmoid(0)

0.5

In [46]:
sigmoid(3)

0.9525741268224334

Aunque por el momento hemos utilizado sigmoid() para recibir números, este también funciona perfectamente bien cuando recibe un arreglo. Al recibir un arreglo, como estamos utilizando np.exp(), sigue funcionando. Esto nos permite calcular multiples activaciones a la vez y nos vendrá bien para construir redes neuronales.

In [48]:
x = np.array([1, 2, 3])
sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

## Feedforward

En el siguiente ejercicio implementaremos la parte llamada Feedforward de una red neuronal.

En este proceso, la red neuronal recibe una entrada, y propaga sus valores multiplicándolos por sus pesos, sumando el bias, y activando las neurona. En este ejercicio implementaremos una red neuronal (técnicamente no, pero es lo que más se asemeja) para el ejercicio de los aplicantes de universidad. 
![title](nn_2_1_student_notation1.png)

In [54]:
# Este es un ejemplo de entrada y pesos de la capa input a la capa output
input = np.array([8.5, 9.5])
weights_input_output = np.array([0.33, 0.25])

print(input)
print(weights_input_output)

[8.5 9.5]
[0.33 0.25]


In [56]:
# Aquí hacemos la combinacion linear
bias = -4.5
linear_combination = input.dot(weights_input_output) + bias
linear_activation

-0.5

In [58]:
# Activamos la neurona con la función sigmoid
result = sigmoid(linear_combination)
result

0.6637386974043525

In [60]:
# TODO: Hacer una función que haga el feedforward para cualquier input
def feed_forward(input):
    """ Función que hace el cálculo 
        TODO: implementa esta función.
        Debe hacer el proceso anterior de multiplicar por los pesos, sumar el bias y activar.
        Usa los valores de arriba para los pesos y el bias
    """
    weights_input_output = 
    bias = 
    return 

In [78]:
# Podemos utilizar este valor para clasificar si aceptamos o no al estudiante. 
# Si es mayor a 0.5, aceptamos al estudiante. Esto es una sobresimplificación.
print(feed_forward(np.array([8.5, 9.5])))
print(feed_forward(np.array([5.5, 6.5])))
print(feed_forward(np.array([4.5, 9.5])))
print(feed_forward(np.array([9.5, 9.5])))
print(feed_forward(np.array([5.5, 9.5])))
print(feed_forward(np.array([8.5, 8.5])))

0.5345841885840448
0.45998862503760274
0.49667291950247183
0.5432802206710214
0.5065360852567379
0.5208770853728153


## Neural Network

En el ejercicio anterior hicimos una red de dos capas. Una de entrada y una de salida. En Deep Learning, trabajamos con capas sobre capas (red profunda). La lógica es la misma, pero un poco más compleja. Implementaremos la siguiente red:
![title](nn_2_3_1_student.png)

In [64]:
input = np.array([8.5, 9.5])
weights_input_hidden = np.array([[0.12, 0.04, 0.08], [0.2, 0.03, 0.05]])

print(input)
print(weights_input_hidden)

[8.5 9.5]
[[0.12 0.04 0.08]
 [0.2  0.03 0.05]]


In [65]:
bias = -2
hidden = sigmoid(input.dot(weights_input_hidden) + bias)
hidden

array([0.71504211, 0.20181322, 0.30048277])

In [66]:
weights_hidden_output = np.array([1.2, 0.2, 0.3])
bias = -0.85
result = sigmoid(hidden.dot(weights_hidden_output) + bias)
result

0.5345841885840448

In [77]:
# TODO: Hacer una función que haga el feedforward para cualquier input
def feed_forward(input):
    """ Función que hace el cálculo """
    weights_input_hidden = np.array([[0.12, 0.04, 0.08], [0.2, 0.03, 0.05]])
    bias_input_hidden = -2
    
    weights_hidden_output = np.array([1.2, 0.2, 0.3])
    bias_hidden_output = -0.85
    
    # TODO: Implementa el valor de las neuronas en la capa oculta y en la capa de salida
    hidden =
    result = 
    
    return result

In [76]:
print(feed_forward(np.array([8.5, 9.5])))
print(feed_forward(np.array([5.5, 6.5])))
print(feed_forward(np.array([4.5, 9.5])))
print(feed_forward(np.array([9.5, 9.5])))
print(feed_forward(np.array([5.5, 9.5])))
print(feed_forward(np.array([8.5, 8.5])))

0.5345841885840448
0.45998862503760274
0.49667291950247183
0.5432802206710214
0.5065360852567379
0.5208770853728153


## Funciones ReLU

En esta parte introduciremos a una nueva funcion de activación. La función ReLU (Rectifier . Relu es muy sencilla y tiene propiedades que han demonstrado ser excelentes en Deep Learning. La red neuronal es la misma que antes. No veras beneficios directamente ahora, pero es bueno que conozcan una segunda función.

![Funcion ReLU](https://qph.ec.quoracdn.net/main-qimg-4229dd280e03b7b3a5dc26c808c4b15b)

In [215]:
def relu(x):
    """
    TODO: Implement relu function
    Use the method np.maximum().
    
    Arguments:
    x: A value
    
    Return:
    s: The relu of x
    """ 
    return 

def feed_forward(input):
    """ Función que hace el cálculo """
    weights_input_output = np.array([[0.12, 0.2], [0.04, 0.03], [0.08, 0.05]]).transpose()
    bias_input_hidden = -2
    
    weights_hidden_output = np.array([[1.2, 0.2, 0.3]]).transpose()
    bias_hidden_output = -0.85
    
    hidden = relu(input.dot(weights_input_hidden) + bias_input_hidden)
    result = sigmoid(hidden.dot(weights_hidden_output) + bias_hidden_output)
    
    return result

In [216]:
print(feed_forward(np.array([8.5, 9.5])))
print(feed_forward(np.array([5.5, 6.5])))
print(feed_forward(np.array([4.5, 9.5])))
print(feed_forward(np.array([9.5, 9.5])))
print(feed_forward(np.array([5.5, 9.5])))
print(feed_forward(np.array([8.5, 8.5])))

[ 0.56316079]
[ 0.29943286]
[ 0.42018841]
[ 0.59820704]
[ 0.45561712]
[ 0.50349994]


# Soluciones

In [79]:
# TODO: Asignar los pesos y el bias para un AND
weight1 = 0.6
weight2 = 0.6
bias = -1

# TODO: Implement sigmoid function
def sigmoid(x):
    # TODO: Implement sigmoid function
    return 1/(1 + np.exp(-x))

# TODO: Calcula la activación linear.
linear_combination = inputs.dot(weights) + bias

# TODO: Activa la neurona utilizando la función sigmoidal que acabas de implementar
output = sigmoid(linear_combination
            
# TODO: Hacer una función que haga el feedforward para cualquier input    
def feed_forward(input):
    """ Función que hace el cálculo 
        TODO: implementa esta función.
        Debe hacer el proceso anterior de multiplicar por los pesos, sumar el bias y activar.
    """
    weights_input_output = np.array([0.33, 0.25])
    bias = -4.5
    return sigmoid(input.dot(weights_input_output) + bias)

# TODO: Hacer una función que haga el feedforward para cualquier input
def feed_forward(input):
    """ Función que hace el cálculo """
    weights_input_hidden = np.array([[0.12, 0.04, 0.08], [0.2, 0.03, 0.05]])
    bias_input_hidden = -2
    
    weights_hidden_output = np.array([1.2, 0.2, 0.3])
    bias_hidden_output = -0.85
    
    # TODO: Implementa el valor de las neuronas en la capa oculta y en la capa de salida
    hidden = sigmoid(input.dot(weights_input_hidden) + bias_input_hidden)
    result = sigmoid(hidden.dot(weights_hidden_output) + bias_hidden_output)
    
    return result
                 
# TODO: Implementa la función ReLU
def relu(x):
    """
    TODO: Implement relu function
    Use the method np.maximum().
    
    Arguments:
    x: A value
    
    Return:
    s: The relu of x
    """ 
    return np.maximum(x, 0)

SyntaxError: invalid syntax (<ipython-input-79-c4a9c53d1b88>, line 18)